#!/usr/bin/bash

set -eoux pipefail

# shims to bypass kernel install triggering dracut/rpm-ostree in fedora43
pushd /usr/lib/kernel/install.d
mv 05-rpmostree.install 05-rpmostree.install.bak
mv 50-dracut.install 50-dracut.install.bak
printf '%s\n' '#!/bin/sh' 'exit 0' > 05-rpmostree.install
printf '%s\n' '#!/bin/sh' 'exit 0' > 50-dracut.install
chmod +x  05-rpmostree.install 50-dracut.install
popd

dnf5 -y copr enable bieszczaders/kernel-cachyos && \
rpm-ostree override remove kernel kernel-core kernel-modules kernel-modules-core kernel-modules-extra  --install kernel-cachyos && \
dnf5 -y copr disable bieszczaders/kernel-cachyos

pushd /usr/lib/kernel/install.d
mv -f 05-rpmostree.install.bak 05-rpmostree.install
mv -f 50-dracut.install.bak 50-dracut.install
popd

dnf5 versionlock add \
    bootc \
    rpm-ostree